### ISSUE TITLE
Node.js module

### ISSUE THREAD

**Issue by Guichaguri** [deskjet/chiptune2.js#16]
It would be useful for any type of application with audio.

The perfect implementation would be a PCM audio stream as the output.
A simple usage of this module:
```
var fs = require('fs');
var Chiptune = require('?');
var Speaker = require('speaker');

fs.createReadStream('file.mod').pipe(new Chiptune()).pipe(new Speaker());
// file.mod will be played
```

I might implement this in a PR by myself, but I want your approval for this idea

**Comment by deskjet** [comment]
I like the idea but it should have its own repository. This project is mostly about wrapping libopenmpt with HTML5 WebAudio API, but that is not available in Node. A Node wrapper would be a completely different thing.

To get started you should set up emscripten and compile libopenmpt to Javascript. It should compile really well. There is an emscripten configuration in libopenmpt's build system.
I'm not sure if emscripten generated files are valid commonJS/Node modules. So that might be a problem you'd have to sort out. Once you have it running inside Node you should be able to use      [libopenmpt's C-API](https://lib.openmpt.org/doc/libopenmpt_c_overview.html).

**Comment by Guichaguri** [comment]
I was testing today to see how I would be able to achieve the result, and for some reason this plays the music with a lot of noise on it. Do you know why?
https://gist.github.com/Guichaguri/3e3126c7c8c68645a2bd#file-node-openmpt-js-L89

**Comment by deskjet** [comment]
Try starting off with mono sound. It's easier.

I wrote a little [example](https://gist.github.com/deskjet/c623226fa47e846eb3fc)
It writes raw audio into a file. The file can be played using the `aplay` or a similar tool like this: `aplay -r 48000 -f S16_LE music.pcm`.

**Comment by Guichaguri** [comment]
Thanks so much, I see how it works now. I got it working with mono, stereo and quad at the same time by using `openmpt_module_get_num_channels`. It's probably better to leave the number of channels configurable to the user anyway :)
