### ISSUE TITLE
Accesssing interactive extensions

### ISSUE THREAD

**Issue by mdahlgrengadd** [deskjet/chiptune2.js#29]
Hi!

Would it possible to access the interactive  extension to control playback tempo?
Can't seem to wrap my head around how this could be done.

Thanks,
Martin

**Comment by deskjet** [comment]
Hi Martin,

i added a little function to help you with that.

https://github.com/deskjet/chiptune2.js/blob/dd530b0561ce4073849194d2a8ed44ee1d1f519f/chiptune2.js#L66-L68

The tempo factor can be changed like this:
 
    player.module_ctl_set('play.tempo_factor', '0.5')

More parameters are listed in the libopenmpt documentation (https://lib.openmpt.org/doc/group__libopenmpt__c.html#ga9a7a95ee4073243b1193120c9107ce99).

Other `libopenmpt` functions can be wrapped in similar fashion. If all the arguements are numbers (pointers are numbers too) functions can be called directly. Otherwise, like in this case, it's easier to use `ccall` or `cwrap`. This method is explained in the emscripten documentation (https://kripken.github.io/emscripten-site/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#interacting-with-code-ccall-cwrap).

**Comment by mdahlgrengadd** [comment]
Yes!! This is awesome! I'll definately have to read up on the wrapping method too.

Many thanks,
Martin.

**Comment by deskjet** [comment]
Great! I'm always glad when I can help.

If you end up adding some useful features feel free to send a pull request.
